version: '3.8'  # Adjust the version if needed

services:
  razortasks:
    image: razortasks
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - razor_tasks_net

  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - razor_tasks_net

networks:
  razor_tasks_net:
    external: true
